language: node_js
sudo: required
services:
  - docker

before_install:
  - docker build -t inviewd/docker-react2 -f Dockerfile.dev .

script:
  - docker run inviewd/docker-react2 npm run test -- --coverage
